### ISSUE TITLE
Require guzzlehttp/guzzle ^7.5

### ISSUE THREAD

**Issue by superromeo** [rvalitov/backlink-checker-php#17]
I use Drupal 10 which require `guzzlehttp/guzzle ^7.5`. This causes conflict.
Is it possible to require `guzzlehttp/guzzle ^7.5`?

**Comment by rvalitov** [comment]
Updated, see the latest version 1.1.0. Does it work for you?

**Comment by superromeo** [comment]
I tried:

>   Problem 1
    - Root composer.json requires rvalitov/backlink-checker-php ~1.1.0 -> satisfiable by rvalitov/backlink-checker-php[1.1.0].
    - nesk/puphpeteer 2.0.0 requires psr/log ^1.0 -> satisfiable by psr/log[1.0.0, ..., 1.1.4].
    - You can only install one version of a package, so only one of these can be installed: psr/log[1.0.0, ..., 1.1.4, 2.0.0, 3.0.0, 3.x-dev].
    - drupal/core 10.0.x-dev requires psr/log ^3.0 -> satisfiable by psr/log[3.0.0, 3.x-dev].
    - rvalitov/backlink-checker-php 1.1.0 requires nesk/puphpeteer 2.* -> satisfiable by nesk/puphpeteer[2.0.0].
    - Root composer.json requires drupal/core 10.0.x-dev as 9.5.0 -> satisfiable by drupal/core[10.0.x-dev].

**Comment by rvalitov** [comment]
Ok thank you, I see the problem is in `psr/log ^1.0`. This dependency goes from the underlying package I use, it's not my direct dependency. I need to think how to solve that. I will come back shortly.

**Comment by rvalitov** [comment]
I had to go to forks of some dependencies because they are not supported anymore. Please try the version 2.0.0. And check the instructions in the [release notes](https://github.com/rvalitov/backlink-checker-php/releases/tag/2.0.0). You need to make some changes to your `composer.json`. Please give me a feedback after you try.

**Comment by superromeo** [comment]
Problem 1
    - Root composer.json requires rvalitov/backlink-checker-php ~2.0.0 -> satisfiable by rvalitov/backlink-checker-php[2.0.0].
    - rvalitov/backlink-checker-php 2.0.0 requires nesk/puphpeteer dev-zoon -> found nesk/puphpeteer[dev-support-all-puppeteer-versions, dev-master, dev-dev, dev-2.0.0-old, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 1.0.0, ..., 1.6.0, 2.0.0] but it does not match the constraint.

**Comment by rvalitov** [comment]
This happens because you didn't update your `composer.json` file as stated in the [release notes](https://github.com/rvalitov/backlink-checker-php/releases/tag/2.0.0). You need to add all the lines.

**Comment by superromeo** [comment]
Thank you!
It installed. But I didn't tried it yet.

**Comment by rvalitov** [comment]
Ok, give it a try. According to my tests with the [demo project](https://github.com/rvalitov/backlink-checker-php-demo) it works the same way.
