### ISSUE TITLE
How can I use this without a pattern?

### ISSUE THREAD

**Issue by novakben** [rvalitov/backlink-checker-php#6]
Can I use this without a pattern?
Just to search for a specific URL:
https://domain.com

**Comment by rvalitov** [comment]
Only Regexp patterns are supported. If you want to convert an URL to regexp, please, use a service like https://regex-escape.com/regex-escaper-online.php
It will escape a specific URL, in your example `https://domain.com` to `https\:\/\/domain\.com`
Does this answer solves your question?
