### ISSUE TITLE
do you have any API for javacript?

### ISSUE THREAD

**Issue by rohan2734** [rvalitov/backlink-checker-php#9]
do you have any API for javacript?

**Comment by rvalitov** [comment]
This project is PHP only. If you work with Javascript, then you can use NodeJS with Puppeteer.

**Comment by rohan2734** [comment]
but i dont have any idea on how to build a backlink checker with nodejs

**Comment by rvalitov** [comment]
You could follow the Puppeteer manual, and then implement your own logic.
I have a proprietary service that checks the backlinks without any knowledge of programming. This service is an a testing phase. If you're interested, I can let you know when it becomes publicly available.

**Comment by rohan2734** [comment]
i am interested in APIs for python and javascript , do let me know
